### ISSUE TITLE
Any instructions how to use?

### ISSUE THREAD

**Issue by Soft-Eyes** [tuya-cloudcutter/cloudcutter-bk7231-haxomatic#1]
Can you provide instructions how to get the app file from device and interpret the output of your script to create a cloudcutter profile?
So i can create and provide the profiles for all.
Thanks!

**Comment by Cossid** [comment]
Closing this ticket, as haxomatic has been integrated and streamlined into a much simpler profiler-builder process.

Please see https://github.com/tuya-cloudcutter/tuya-cloudcutter/tree/main/profile-building for more information.
